Repository microsoft/MIEngine, pull requests merged in 2020-09, with the labels that each got.

#1028 Support HandleReadMemoryRequestAsync
  src/MIDebugEngine/AD7.Impl/AD7Engine.cs
  src/Microsoft.VisualStudio.Debugger.Interop.DAP/Microsoft.VisualStudio.Debugger.Interop.DAP.cs
  src/OpenDebugAD7/AD7DebugSession.cs
  src/OpenDebugAD7/AD7Resources.Designer.cs
  src/OpenDebugAD7/AD7Resources.resx
  src/OpenDebugAD7/AD7Utils.cs
  src/OpenDebugAD7/VariableManager.cs
Labels: Feature Request

#1046 Fixed ps call for Docker Linux containers
  src/SSHDebugPS/PSOutputParser.cs
Labels: bug

#1051 Add SymbolLoadInfo for LaunchOptionJson
  src/MICore/JsonLaunchOptions.cs
  src/MICore/LaunchOptions.cs
Labels: enhancement
