Repository microsoft/MIEngine, pull requests merged in 2020-10, with the labels that each got.

#1055 Fix SourceFileMap in MICore
  src/MICore/CommandFactories/MICommandFactory.cs
  src/MICore/LaunchOptions.cs
  src/MICore/MICoreResources.Designer.cs
  src/MICore/MICoreResources.resx
  src/MICore/PlatformUtilities.cs
  src/MIDebugEngine/Engine.Impl/CygwinFileMapper.cs
  src/MIDebugEngine/Engine.Impl/DebuggedProcess.cs
  src/MIDebugEngine/Engine.Impl/MITextPosition.cs
Labels: enhancement

#1054 [GDB] Support Modules window for OpenDebugAD7 scenarios
  src/MIDebugEngine/AD7.Impl/AD7Module.cs
  src/MIDebugEngine/MIDebugEngine.csproj
  src/OpenDebugAD7/AD7DebugSession.cs
  src/OpenDebugAD7/OpenDebugAD7.csproj
  src/OpenDebugAD7/packages.config
Labels: Feature Request

#1056 XML Translation Removal
  src/MICore/JsonLaunchOptions.cs
  src/MICore/LaunchOptions.cs
  src/MIDebugEngine/Engine.Impl/DebuggedProcess.cs
  src/OpenDebugAD7/AD7DebugSession.cs
  src/OpenDebugAD7/MILaunchOptions.cs
  src/OpenDebugAD7/OpenDebugAD7.csproj
  src/OpenDebugAD7/PathConverter.cs
  src/OpenDebugAD7/PathMapper.cs
Labels: enhancement

#1067 Removing old Checksum Code for ClrDbg
  src/OpenDebugAD7/AD7Impl/AD7DocumentPosition.cs
  src/OpenDebugAD7/Document.cs
  src/OpenDebugAD7/OpenDebugAD7.csproj
Labels: enhancement

#1068 Remove references to building with mono framework
  build/miengine.settings.targets
  build/miengine.targets
  src/DebugEngineHost.VSCode/DebugEngineHost.VSCode.csproj
  src/MICore/GenerateXmlSerializersAssembly.targets
  src/OpenDebugAD7/OpenDebugAD7.csproj
  src/WindowsDebugLauncher/WindowsDebugLauncher.csproj
  src/prebuild/prebuild.csproj
Labels: enhancement

#1070 Fix DebugServerPath for JSON parsing
  src/MICore/LaunchOptions.cs
Labels: bug

#1072 Set SetupCommands to be common for JSON parsing
  src/MICore/JsonLaunchOptions.cs
  src/MICore/LaunchOptions.cs
Labels: bug
