Repository microsoft/MIEngine, pull requests merged in 2022-01, with the labels that each got.

#1038 avoid "Unable to open file" popups caused by missing source code
  src/OpenDebugAD7/AD7DebugSession.cs
Labels: Feature Request

#1155 Send unix styled paths for Cygwin GDB sessions
  src/MIDebugEngine/Engine.Impl/CygwinFileMapper.cs
  src/MIDebugEngine/Engine.Impl/DebuggedProcess.cs
  src/MIDebugEngine/Engine.Impl/Disassembly.cs
  src/MIDebugEngine/Engine.Impl/SourceLine.cs
Labels: bug, VS, VS Code

#1257 Data breakpoints in OpenDebugAD7
  src/DebugEngineHost.VSCode/HostMarshal.cs
  src/DebugEngineHost.VSCode/VSCode/EngineConfiguration.cs
  src/MIDebugEngine/AD7.Impl/AD7PendingBreakpoint.cs
  src/MIDebugEngine/AD7.Impl/AD7Property.cs
  src/OpenDebugAD7/AD7DebugSession.cs
  src/OpenDebugAD7/AD7Impl/AD7BreakPointRequest.cs
  src/OpenDebugAD7/AD7Resources.Designer.cs
  src/OpenDebugAD7/AD7Resources.resx
  src/OpenDebugAD7/VariableManager.cs
  src/OpenDebugAD7/cppdbg.ad7Engine.json
Labels: Feature Request, VS Code
