Repository microsoft/MIEngine, pull requests merged in 2022-08, with the labels that each got.

#1334 Only print evaluate requests in REPL context
  src/MIDebugEngine/Engine.Impl/Variables.cs
Labels: VS Code

#1337 [#1336] Discard cached state after program starts stepping.
  src/OpenDebugAD7/AD7DebugSession.cs
Labels: bug

#1338 Upgrading VSSDK: 17.0.1600 ->17.3.2093
  build/package_versions.settings.targets
Labels: dependencies

#1344 Address visualizing past 1000 ArrayItems
  src/MIDebugEngine/Natvis.Impl/Natvis.cs
  test/CppTests/Tests/NatvisTests.cs
  test/CppTests/debuggees/natvis/src/main.cpp
Labels: bug, debugger
